config/routes.rb
Rails.application.routes.draw do
  resources :handelbars, only: :index
  root 'home#index'
  get "games/games_score", to: 'games#games_score'
  get '/users/games_users_played', to: 'users#games_users_played'
  get '/users/quizzes_user_created', to: 'users#quizzes_user_created'
  get '/quizzes/comment_form', to: 'quizzes#comment_form'
  get '/quizzes/categories', to: 'categories#index'
  get '/categories/searchbar', to: 'categories#searhBar'

  resources :quizzes

  resources :users, only: [:new, :create, :index, :show]

  get "quizzes/top_quizzes", to: 'quizzes#top_quizzes'

  resources :quizzes, only: :index do
    resources :categories, path: "/", :only => [:index, :show]
  end


  resources :quizzes, only: :show do
  	resources :games, only: [:new, :show]
  end



  resources :quizzes, only: :show do
    resources :comments, only: :create
  end


  resources :games, only: :create


  get "/login", to: 'sessions#new'
  post "/login",  to:'sessions#create'
  delete "logout",  to: 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :games
  has_many :question_and_answers
  has_many :quiz_categories
  has_many :categories, through: :quiz_categories
  has_many :comments
  has_many :users, through: :comments
  has_many :users, through: :games

  validate :must_have_question_and_answer
  validates :name, presence: true
  validates :categories, presence: true

  accepts_nested_attributes_for :question_and_answers, reject_if: :all_blank

	#class method to see what quizzes have been played the most
  scope :most_games, -> {joins(:games).group(:id).order("COUNT(games.id) DESC").limit(5)}
  #class method to filter by category given in the argument
	#scope :by_category, -> (category_id){joins(:categories).where("categories.id=?", category_id)}
  scope :by_category, -> (category_name){joins(:categories).where("categories.name=?", category_name)}
  #class mehod to show top 5 scores per game
	scope :top_5_scores, -> (quiz){joins(:games).where quiz_id = "?", quiz.id}
  #custom category attribute writer - doesn't duplicate and doesn't save blank
	def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      if category_attribute[:name] != ""
        category = Category.find_or_create_by(category_attribute)
        self.categories << category
      else
        return errors
      end
    end
  end

#creates an array of answers from quiz to compare to array of guesses
  def correct_answers
  	self.question_and_answers.collect{|qa| qa.answer}
  end


private
  #custom validator for 5 questions and answers when creating quiz
  def must_have_question_and_answer
    return errors.add :base, "Must Have 5 Questions and Answers" unless question_and_answers.length == 5
  end


end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :require_login, only:[:index,:new,:top_quizzes, :show]
  before_action  :set_quiz, only:[:show, :edit, :update, :destroy, :quiz_owner]
  before_action :quiz_owner, only:[:edit, :update, :destroy]

  def index
    @quizzes = Quiz.all

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @quizzes, status: 200}
    end
  end

  def new
  	@quiz = Quiz.new
  end

#shows page top 5 quizzes by times played
  def top_quizzes
    @quizzes = Quiz.most_games
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @quiz, status: 200}
    end
  end


  def create
  	@quiz = Quiz.new(quiz_params)
    @quiz.user_id = current_user.id
    if
    @quiz.save
      render json: @quiz, status: 201

      else
       render :new
     end
   end

  def edit

  end

  def update
    @quiz.update(quiz_params)
    flash[:message]="Quiz updated!"
    redirect_to @quiz
  end

  def destroy
    @quiz.destroy
    flash[:message]="Quiz deleted!"
    redirect_to user_path(User.find(session[:user_id]))
  end

 def comment_form
   @quiz = Quiz.find_by(id: params[:quiz_id])
   render 'quizzes/comment_form', layout: false
 end


  private

  def quiz_params
    params.require(:quiz).permit(:name, category_ids:[], categories_attributes: [:name], question_and_answers_attributes: [:question, :answer, :id])
  end
#finds correct quiz by params
  def set_quiz
    @quiz = Quiz.find_by(id: params[:id])
  end
#verifies quiz owner to allow edit
  def quiz_owner
    if @quiz.user_id != current_user.id
      redirect_to quiz_path(@quiz)
    end
  end

end

app/helpers/quizzes_helper.rb
module QuizzesHelper

  def flash_message
    if flash[:message]
      flash[:message]
    end
  end

  def user_created_quiz?
    @quiz.user_id == current_user.id
  end
end

app/views/quizzes/_answer_show_page.html.erb
<h1> <%= @quiz.name %> </h1>

<ol>
  <p>Categories: <% @quiz.categories.each do|category| %>
     <%= category.name %>
  <% end %></p>

<% @quiz.question_and_answers.each do |qa| %>
    <li>Question: <%= qa.question %>
        <br>
        Answer: <%= qa.answer %></li>
    <% end %>
  </ol>
  <%= link_to "Edit Quiz", edit_quiz_path,class: "btn btn-warning btn-light" %>
  <br>
  <br>

app/views/quizzes/_categories.html.erb
<div class="form-group">
  Categories
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, class: "form-control" %>
  <br>
</div>

<div class="form-group">
New Category
  <%= f.fields_for :categories, @quiz.categories.build do |categories_fields| %>
  <%= categories_fields.text_field :name, class: "form-control" %>
</div>
  <% end %>

app/views/quizzes/_comments.html.erb
<div class="comment-list">
  <% @quiz.comments.each do |comment| %>
    <p><%= link_to comment.user.username, user_path(comment.user) %> said:
    <%= comment.content %></p>
  <% end %>
</div>
<%= link_to "Add a new Comment", quizzes_comment_form_path(quiz_id: @quiz.id), id:"add-comment" %>

<div class="new-comment-form"></div>

app/views/quizzes/_form.html.erb
<%= form_for @quiz do |f| %>
<% if @quiz.errors.any? %>

    <div class="alert alert-info" role="alert">
      <%= f.error_messages %>
    </div>
<% end %>
    <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %></div>
    <br>

    <%= render 'categories', f: f %>
   <br>

    <%= render 'questions_and_answers', f: f %>


    <div id="create_quiz"> <%= f.submit "Create Quiz",class: "btn btn-primary btn-light" %></div>
<% end %>

app/views/quizzes/_questions_and_answers.html.erb
<div class="form-group">

<ol>
  <!-- uses helper to control field numbers to only be 5 -->
  <% f.build_nested_records(:question_and_answers, minimum: 5, maximum: 5) %>
    <%= f.fields_for :question_and_answers do |q_and_a| %>

      <li><%= q_and_a.label :question %>
      <%= q_and_a.text_field :question, class: "form-control" %><br>
      <%= q_and_a.label :answer %>
      <%= q_and_a.text_field :answer, class: "form-control" %><br></li>
     <% end %>
     </ol>
</div>

app/views/quizzes/_quiz_table.html.erb
  <table class="table list-quizzes">
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><strong>Quiz Name</strong></td>
        <td><strong>Quiz Created By:</strong></td>
        <td><strong>Top Score</strong></td>
      </tr>
      <div class="list-quizzes">
      <% @quizzes.each do |quiz| %>
        <tr>

          <td><%= link_to quiz.name, quiz_path(quiz), class: "indv-quiz", id: "quiz-#{quiz.id}" %></td>
          <td><%= quiz.user.username %></td>
              <% if  Game.top_score(quiz).first %>
                          <!-- top score for game -->
                <td> <%= Game.top_score(quiz).first.score %></td>
              <% else %>
                 <td>This Game Hasn't Been Played </td>
              <% end %>

        </tr>
      </div>
      <% end %>
    </tbody>
  </table>

app/views/quizzes/_top_score_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><strong>User Name</strong></td>
      <td><strong>Score</strong></td>
    </tr>

    <% Game.top_5_scores(@quiz).each do |game| %>
    <tr>
    <td>User: <%= link_to game.user.username, user_path(game.user) %></td>
    <td>Score: <%= game.score %></td>
    <% end %>

    </tr>

  </tbody>
</table>

app/views/quizzes/comment_form.html.erb
<%= form_for [@quiz, @quiz.comments.build] do |f| %>
  <%= f.text_area :content %>
  <%= f.button :submit,class: "btn btn-primary btn-light" %>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Edit Quiz</h1>


<%= render 'form' %>

app/views/quizzes/index.html.erb
<div id="quiz-index">

<div class="center" >
  <h1> Check Out The Most Popular Quizzes!! </h1>
  <h2> <%= link_to "Top Quizzes",  quizzes_top_quizzes_path, class: "btn btn-success btn-lg btn-block" %> </h2>
  <h1> See All Games Played and the Top Scores!!!</h1>
    <h2> <%= link_to "Game Scores",   games_games_score_path, class: "btn btn-primary btn-lg btn-block" %> </h2>
  <h2> All Quizzes Available! </h2>
</div>

<%= render 'quiz_table' %>

</div>

app/views/quizzes/new.html.erb
<div id="quiz-form">
<h1>Create a new Quiz!</h1>

<%= render 'form' %>
</div>

app/views/quizzes/show.html.erb
<%   if flash[:message] %>
<div class="alert alert-success" role="alert">
  <%= flash_message %>
</div>
<% end %>

<div class="center">
  <% if user_created_quiz? %>
    <%= render 'answer_show_page', quiz: @quiz %>
    <%= form_tag quiz_path(@quiz.id), method: "delete" do %>
       <%= submit_tag "DELETE Quiz",class: "btn btn-danger btn-light" %>
    <% end %>
    <br>
     <%= link_to "All Quizzes", quizzes_path,class: "btn btn-primary" %>
<% else %>
 <div class="center">

 <h1> <%= @quiz.name %> </h1>
 <h2> Quiz created by <%= link_to @quiz.user.username, user_path(@quiz.user) %></h2>

 <p>Categories: <% @quiz.categories.each do|category| %>
    <%= category.name %>
    <% end %></p>

  <h3><strong> Would you like to<br>
    <%=link_to "TAKE THIS QUIZ?",  new_quiz_game_path(@quiz.id), class: "btn btn-success btn-lg" %> <h3>
</div>
<% end %>
<%= link_to "load quiz", quiz_path(@quiz),id: "load-quiz" %>
<div class="ordered-quiz"></div>
<h2>Top Scores:</h2>
<%= render 'top_score_table' %>

<br>
<p>Comments: </p>
<%= render 'comments' %>

app/views/quizzes/top_quizzes.html.erb
<div class="center">
<h1> Top 5 Most Popular Quizes </h1>
</div>

<%= render 'quiz_table' %>