config/routes.rb
Rails.application.routes.draw do
  resources :handelbars, only: :index
  root 'home#index'
  get "games/games_score", to: 'games#games_score'
  get '/users/games_users_played', to: 'users#games_users_played'
  get '/users/quizzes_user_created', to: 'users#quizzes_user_created'
  get '/quizzes/comment_form', to: 'quizzes#comment_form'
  get '/quizzes/categories', to: 'categories#index'
  get '/categories/searchbar', to: 'categories#searhBar'

  resources :quizzes

  resources :users, only: [:new, :create, :index, :show]

  get "quizzes/top_quizzes", to: 'quizzes#top_quizzes'

  resources :quizzes, only: :index do
    resources :categories, path: "/", :only => [:index, :show]
  end


  resources :quizzes, only: :show do
  	resources :games, only: [:new, :show]
  end



  resources :quizzes, only: :show do
    resources :comments, only: :create
  end


  resources :games, only: :create


  get "/login", to: 'sessions#new'
  post "/login",  to:'sessions#create'
  delete "logout",  to: 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :quiz
  has_many :guesses
  accepts_nested_attributes_for :guesses, reject_if: :all_blank

  #class methods show top 5 scores of quiz and the top score of the quiz
  scope :top_5_scores, ->(quiz){order(score: :desc).limit(5).where("quiz_id = ?", quiz.id)}
  scope :top_score, ->(quiz){order(score: :desc).limit(1).where("quiz_id = ?", quiz.id)}

  scope :order_by_score, -> {order(score: :desc)}
  def play_game #compares answers and updates score for game
    game_score = (quiz.correct_answers & user_guesses).count
    self.score = game_score
    self.save
  end

  def user_guesses # turns guesses into an array
    self.guesses.collect{|g| g.guess}
  end



end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_login

#load game form and build empty guess fields
  def new
    @game = Game.new(quiz_id: params[:quiz_id])
    @quiz = Quiz.find_by(id: params[:quiz_id])
    @game.guesses.build
  end

#game play- compares answers and returns sore on game show page
  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id
    @game.save
    @game.play_game
    redirect_to quiz_game_path(@game.quiz, @game)
  end

  def show
    @game = Game.find_by(id: params[:id])
  end

  def games_score
    @games = Game.order_by_score
  end

 private
  def game_params
    params.require(:game).permit(:quiz_id, guesses_attributes: [:guess])
  end
end

app/views/games/games_score.html.erb
<div class="center">

<h1> All Games Played By Score </h1>


</div>


<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><strong>Quiz Name</strong></td>
      <td><strong>Game Score:</strong></td>
      <td><strong>User </strong></td>
    </tr>
    <% @games.each do |game| %>
      <tr>

        <td><%= link_to game.quiz.name, quiz_path(game.quiz) %></td>
        <td> <%= game.score %></td>
        <td><%= link_to game.user.username, user_path(game.user) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<div class= "center">
<h1>Take the <%= @quiz.name %> Quiz!!</h1>
<h2> Quiz created by <%= link_to @quiz.user.username, user_path(@quiz.user) %></h2>
</div>
<%= form_for @game do |f| %>
<%= f.hidden_field :quiz_id %>
<% @quiz.question_and_answers.each do |qa| %>
<div class="form-group">
Question: <%= qa.question %>
         <%= f.fields_for :guesses do |g| %>
           <br><%= g.label :guess, "Answer" %>
           <%= g.text_field :guess, class: "form-control" %>
        <% end %>
</div>
<% end %>

<%= f.submit "Take Quiz",class: "btn btn-primary btn-light" %>
<% end %>

app/views/games/show.html.erb
<div class="center">
<h1> <%= @game.quiz.name %> Quiz Results </h1>

<div class="alert alert-success" role="alert">
  <h1>Congratulations you scored: <%= @game.score %><h1>
</div>

<h2>Would you like to try a again?</h2>
</div>

<div class="center">
  <%= link_to "Try Again", new_quiz_game_path(@game.quiz_id), class: "btn btn-primary btn-lg btn-block" %>
  <br>
  <br>
</div>

<div class="center">
  <h2>Try Another Quiz</h2>
  <%= link_to 'All Quizzes', quizzes_path,class: "btn btn-info btn-lg btn-block" %>
</div>