config/routes.rb
Rails.application.routes.draw do
  resources :handelbars, only: :index
  root 'home#index'
  get "games/games_score", to: 'games#games_score'
  get '/users/games_users_played', to: 'users#games_users_played'
  get '/users/quizzes_user_created', to: 'users#quizzes_user_created'
  get '/quizzes/comment_form', to: 'quizzes#comment_form'
  get '/quizzes/categories', to: 'categories#index'
  get '/categories/searchbar', to: 'categories#searhBar'

  resources :quizzes

  resources :users, only: [:new, :create, :index, :show]

  get "quizzes/top_quizzes", to: 'quizzes#top_quizzes'

  resources :quizzes, only: :index do
    resources :categories, path: "/", :only => [:index, :show]
  end


  resources :quizzes, only: :show do
  	resources :games, only: [:new, :show]
  end



  resources :quizzes, only: :show do
    resources :comments, only: :create
  end


  resources :games, only: :create


  get "/login", to: 'sessions#new'
  post "/login",  to:'sessions#create'
  delete "logout",  to: 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="container">
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
<a class="navbar-brand" href="<%= root_url %>">Home</a>
</div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <% if current_user %>

             <li><%= link_to "Create Quiz", new_quiz_path %></li>
             <li><%= link_to "Log Out", logout_path, method: :delete %></li>



           <% else %>
             <li><%= link_to "Sign Up", new_user_path %></li>
             <li><%= link_to "Log In", login_path %></li>
           <% end %>
         </ul>



</div>
<div class="navbar-collapse collapse">
  <ul class="nav navbar-nav">

  </ul>
</div><!--/.nav-collapse -->
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TriviaTown</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.11/handlebars.min.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <header>
    <!-- load navbar partial-->
    <%= render "layouts/navbar" %>


  </header>

  <body>
    <div class="page-body">
  <!-- content -->
    <div class="center">
      <div id="createdQuiz">
        <h2 id="quizName"></h2>
        <p id="categories"></p>
        <p id="question1"></p>
        <p id="answer1"></p>
        <p id="question2"></p>
        <p id="answer2"></p>
        <p id="question3"></p>
        <p id="answer3"></p>
        <p id="question4"></p>
        <p id="answer4"></p>
        <p id="question5"></p>
        <p id="answer5"></p>

   <footer></footer>
    </div>
  </div>
</div>

    <%= yield %>
  </body>
</html>